# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eod.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, validators=[eod.models._validate_known_type])),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EndOfDayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('story_id', models.CharField(max_length=30)),
                ('status', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='End of day item done date')),
                ('is_sent', models.BooleanField(default=False)),
                ('contributors', models.ManyToManyField(to='eod.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_active', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='endofdayitem',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eod.Team'),
        ),
        migrations.AddField(
            model_name='dispatchrule',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eod.Team'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='teams',
            field=models.ManyToManyField(to='eod.Team'),
        ),
    ]
