# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
